apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana-plugin
  description: An example for Grafana integration.
  annotations:
    grafana/dashboard-selector: 'general'
    grafana/alert-label-selector: 'type=http-requests'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
