apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana-plugin
  description: An example for Grafana integration.
  annotations:
    grafana/dashboard-selector: 'general'
    grafana/alert-label-selector: 'type=http-requests'
    prometheus.io/rule: memUsage|component,node_memory_active_bytes|instance,sum by (instance) (node_cpu_seconds_total)
    prometheus.io/alert: all
spec:
  type: service
  lifecycle: experimental
  owner: default-team
